import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { isValidRoomCode, normalizeRoomCode, type RoomSummary } from "@crafttogether/shared";
import { Badge, Button, Card, Screen, SectionHeader, Subtitle, Title } from "@/components/ui";
import { colors, radius, spacing } from "@/theme";
import { api, ApiError, NetworkError, wakeBackend } from "@/api/client";
import { getPlayerName } from "@/state/session";
import { setActiveSession } from "@/state/active";
import { discoverLanWorlds, type LanWorld } from "@/net/lanDiscovery";
import { library } from "@/state/library";
const GUEST_LOCAL_PORT = 19140;
export default function Rooms() {
  const router = useRouter(); const [rooms,setRooms]=useState<RoomSummary[]>([]); const [lan,setLan]=useState<LanWorld[]>([]); const [code,setCode]=useState(""); const [query,setQuery]=useState(""); const [loading,setLoading]=useState(true); const [joining,setJoining]=useState(false); const [favorites,setFavorites]=useState<string[]>([]); const [error,setError]=useState<string|null>(null); const refreshing=useRef(false);
  const refresh=useCallback(async()=>{ if(refreshing.current)return; refreshing.current=true; setLoading(true); setError(null); try { await wakeBackend({maxWaitMs:70000}); const list=await api.listRooms(); setRooms(list.rooms); setLan(await discoverLanWorlds().catch(()=>[])); } catch(e) { setError(e instanceof NetworkError?"Servidor indisponível. Verifique sua conexão e tente novamente.":"Não foi possível carregar os servidores."); } finally { refreshing.current=false; setLoading(false); } },[]);
  useEffect(()=>{ refresh(); library.getFavorites().then(setFavorites).catch(()=>undefined); },[refresh]);
  const join=async(value:string)=>{const normalized=normalizeRoomCode(value); if(!isValidRoomCode(normalized)){setError("Código inválido. Use 6 caracteres.");return;} setJoining(true);setError(null); try {await wakeBackend();const guestName=(await getPlayerName())||"Amigo";const res=await api.joinRoom({code:normalized,guestName});await library.addRecent(res.room.id);setActiveSession({role:"guest",room:res.room,token:res.guestToken,relay:res.relay,localPort:GUEST_LOCAL_PORT});router.replace(`/room/${res.room.id}`);}catch(e){setError(e instanceof NetworkError?"Servidor indisponível. Tente novamente.":e instanceof ApiError&&e.code==="room_not_found"?"Servidor não encontrado.":e instanceof ApiError&&e.code==="room_full"?"Este servidor está cheio.":"Não foi possível entrar.");}finally{setJoining(false);}};
  const visible=useMemo(()=>rooms.filter(r=>r.name.toLowerCase().includes(query.toLowerCase())||r.hostName.toLowerCase().includes(query.toLowerCase())),[rooms,query]);
  const toggle=async(id:string)=>setFavorites(await library.toggleFavorite(id));
  return <Screen><Title>Servidores</Title><Subtitle>Encontre um mundo para jogar agora ou entre usando um código de convite.</Subtitle><Card><Text style={styles.label}>ENTRAR POR CÓDIGO</Text><View style={styles.row}><TextInput value={code} onChangeText={t=>setCode(t.toUpperCase())} placeholder="Ex: K7Q2MP" placeholderTextColor={colors.textMuted} autoCapitalize="characters" maxLength={6} style={[styles.input,{flex:1}]}/><Button label="Entrar" onPress={()=>join(code)} loading={joining}/></View></Card>{error&&<Text style={styles.error}>{error}</Text>}<View style={styles.searchRow}><TextInput value={query} onChangeText={setQuery} placeholder="Pesquisar servidores" placeholderTextColor={colors.textMuted} style={[styles.input,{flex:1}]}/><Pressable onPress={refresh} accessibilityRole="button"><Text style={styles.action}>Atualizar</Text></Pressable></View><SectionHeader title="Servidores públicos" action={`${visible.length} online`} />{loading?<ActivityIndicator color={colors.primary}/>:visible.length===0?<Card><Text style={styles.emptyTitle}>Nenhum servidor encontrado</Text><Text style={styles.empty}>Tente outra busca ou crie sua própria sala.</Text></Card>:visible.map(room=><Card key={room.id}><View style={styles.cardTop}><Text style={styles.roomName}>{room.name}</Text><Pressable onPress={()=>toggle(room.id)}><Text style={styles.star}>{favorites.includes(room.id)?"★":"☆"}</Text></Pressable></View><View style={styles.metaRow}><Badge tone="success">ONLINE</Badge><Text style={styles.meta}>{room.guestCount+1}/{room.maxGuests+1} jogadores</Text><Text style={styles.meta}>Público</Text></View><Text style={styles.meta}>Host: {room.hostName} · Código {room.code}</Text><Button label="Entrar no servidor" onPress={()=>join(room.code)}/></Card>)}{lan.length>0&&<><SectionHeader title="Na sua rede local"/>{lan.map(w=><Card key={`${w.address}:${w.port}`}><Text style={styles.roomName}>{w.name}</Text><Text style={styles.meta}>{w.address}:{w.port} · Descoberto na LAN</Text></Card>)}</>}</Screen>;
}
const styles=StyleSheet.create({label:{color:colors.textMuted,fontSize:11,fontWeight:"800",letterSpacing:1},input:{backgroundColor:colors.bg,borderColor:colors.cardBorder,borderWidth:1,borderRadius:radius.sm,color:colors.text,paddingHorizontal:spacing.md,paddingVertical:12,fontSize:15},row:{flexDirection:"row",alignItems:"center",gap:spacing.sm},searchRow:{flexDirection:"row",alignItems:"center",gap:spacing.sm},action:{color:colors.accent,fontWeight:"800",fontSize:13},error:{color:colors.danger,fontSize:14},roomName:{color:colors.text,fontSize:18,fontWeight:"800",flex:1},cardTop:{flexDirection:"row",alignItems:"center"},star:{color:colors.accent,fontSize:28},metaRow:{flexDirection:"row",alignItems:"center",gap:spacing.sm},meta:{color:colors.textMuted,fontSize:13},emptyTitle:{color:colors.text,fontSize:16,fontWeight:"800"},empty:{color:colors.textMuted,fontSize:13,lineHeight:19}});
